language: perl
perl:
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
notifications:
  email:
    - tf.900913@gmail.com
script: perl Makefile.PL && make && cover -test
after_success:
    - cover -report coveralls
before_install:
    - cpanm Module::Install::Repository
    - cpanm Module::Install::ReadmeFromPod
    - cpanm Module::Install::CPANfile
    - cpanm Module::Install::AuthorTests
    - cpanm -n git://github.com/kan/coveralls-perl.git